CREATE TYPE "Role" AS ENUM ('STUDENT', 'GUARDIAN', 'ADMIN');
CREATE TYPE "CommercialStage" AS ENUM ('BUYER', 'LEAD', 'PAYER', 'CUSTOMER', 'TURNED');
CREATE TYPE "PaymentChannel" AS ENUM ('CARD', 'YAPE', 'PLIN');
CREATE TYPE "TransactionStatus" AS ENUM ('INICIADA', 'PENDIENTE', 'CONFIRMADA', 'RECHAZADA', 'VENCIDA', 'EN_REVISION');
CREATE TYPE "AccessStatus" AS ENUM ('PENDIENTE', 'ACTIVADO', 'SUSPENDIDO', 'INCIDENCIA');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"nombres" TEXT NOT NULL,"apellidos" TEXT NOT NULL,"email" TEXT NOT NULL UNIQUE,"passwordHash" TEXT NOT NULL,"telefono" TEXT,"rol" "Role" NOT NULL DEFAULT 'STUDENT',"etapaComercial" "CommercialStage" NOT NULL DEFAULT 'BUYER',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "StudentProfile" ("userId" TEXT PRIMARY KEY,"edad" INTEGER,"nivelEducativo" TEXT,"carreraInteres" TEXT,"areaRefuerzo" TEXT,"fechaExamen" TIMESTAMP(3));
CREATE TABLE "GuardianProfile" ("userId" TEXT PRIMARY KEY,"relacionConEstudiante" TEXT,"autorizadoContacto" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "StudentGuardian" ("studentId" TEXT NOT NULL,"guardianId" TEXT NOT NULL,PRIMARY KEY ("studentId","guardianId"));
CREATE TABLE "Plan" ("id" TEXT PRIMARY KEY,"nombre" TEXT NOT NULL UNIQUE,"descripcion" TEXT NOT NULL,"precioMensual" DOUBLE PRECISION NOT NULL,"precioSemestral" DOUBLE PRECISION,"diasPrueba" INTEGER NOT NULL DEFAULT 0,"activo" BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE "Subscription" ("id" TEXT PRIMARY KEY,"studentId" TEXT NOT NULL,"planId" TEXT NOT NULL,"fechaInicio" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"fechaFin" TIMESTAMP(3) NOT NULL,"estadoAcceso" "AccessStatus" NOT NULL DEFAULT 'PENDIENTE',"estadoOnboarding" TEXT NOT NULL DEFAULT 'PENDIENTE');
CREATE TABLE "Payment" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"subscriptionId" TEXT,"planId" TEXT NOT NULL,"canalPago" "PaymentChannel" NOT NULL,"monto" DOUBLE PRECISION NOT NULL,"estadoTransaccion" "TransactionStatus" NOT NULL DEFAULT 'INICIADA',"codigoOperacion" TEXT NOT NULL UNIQUE,"fechaInicio" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"fechaConfirmacion" TIMESTAMP(3),"autorizacionRecurrencia" BOOLEAN NOT NULL DEFAULT false);
CREATE TABLE "PaymentAttempt" ("id" TEXT PRIMARY KEY,"paymentId" TEXT NOT NULL,"canalPago" "PaymentChannel" NOT NULL,"estado" TEXT NOT NULL,"detalle" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "StudentProfile" ADD CONSTRAINT "StudentProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON UPDATE CASCADE;
ALTER TABLE "GuardianProfile" ADD CONSTRAINT "GuardianProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON UPDATE CASCADE;
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "StudentProfile"("userId") ON UPDATE CASCADE;
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_subscriptionId_fkey" FOREIGN KEY ("subscriptionId") REFERENCES "Subscription"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON UPDATE CASCADE;
ALTER TABLE "PaymentAttempt" ADD CONSTRAINT "PaymentAttempt_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "Payment"("id") ON UPDATE CASCADE;
